// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGGhZxI27s9-3IxMFbGH4GdgSH2JGAek',
    appId: '1:92129078212:web:3c82ed5892764ced4ad291',
    messagingSenderId: '92129078212',
    projectId: 'queueingtool',
    authDomain: 'queueingtool.firebaseapp.com',
    storageBucket: 'queueingtool.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX6L-EgpSzBVEDcXXCq5oXoQo1aFeUiwY',
    appId: '1:92129078212:android:3a5e2508e90e38ea4ad291',
    messagingSenderId: '92129078212',
    projectId: 'queueingtool',
    storageBucket: 'queueingtool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb43knWnvduL9YC4FZDPUyVM51f819ZUQ',
    appId: '1:92129078212:ios:4d61e65adfa322df4ad291',
    messagingSenderId: '92129078212',
    projectId: 'queueingtool',
    storageBucket: 'queueingtool.appspot.com',
    iosBundleId: 'com.example.queueingtool',
  );
}
